-- Etapa 6 - cerinta individuala, punctul 3:
-- minimum 15-20 de produse suficient de diverse pentru toate filtrele si sortarile.
INSERT INTO produse
  (nume, descriere, imagine, categorie, subcategorie, pret, scor_performanta, data_adaugare, culoare, conectivitate, in_stoc)
VALUES
  ('Placă de bază Forge B650', 'Platformă ATX pentru configurații AMD moderne, cu extensii rapide și traseu aerisit.', '/resurse/imagini/galerie/originale/placa-baza-desktop.jpg', 'componente', 'placa-de-baza', 899.90, 82, '2026-05-02', 'negru', ARRAY['PCIe', 'USB-C', 'Ethernet'], TRUE),
  ('Placa de baza Forge Mini-ITX', 'Placa compacta pentru sisteme de dimensiuni reduse, fara compromisuri de conectivitate.', '/resurse/imagini/galerie/originale/placa-baza-mini-itx.jpg', 'componente', 'placa-de-baza', 749.50, 76, '2026-04-18', 'negru', ARRAY['PCIe', 'Wi-Fi', 'USB-C'], TRUE),
  ('Placa de baza Retro AT', 'Model demonstrativ pentru prezentarea evolutiei arhitecturii calculatoarelor desktop.', '/resurse/imagini/galerie/originale/placa-baza-at.jpg', 'componente', 'placa-de-baza', 299.00, 25, '2025-11-10', 'gri', ARRAY['AT', 'PS/2'], FALSE),
  ('Placa video Forge Vision 8G', 'Accelerator grafic echilibrat pentru jocuri Full HD si aplicatii creative.', '/resurse/imagini/galerie/originale/placa-video-matrox.jpg', 'componente', 'placa-video', 1699.99, 88, '2026-05-20', 'negru', ARRAY['PCIe', 'HDMI', 'DisplayPort'], TRUE),
  ('Placa video Forge Studio 12G', 'Solutie grafica pentru randare, editare video si lucru pe mai multe monitoare.', '/resurse/imagini/galerie/originale/placa-video-matrox.jpg', 'componente', 'placa-video', 2399.00, 94, '2026-03-14', 'negru', ARRAY['PCIe', 'HDMI', 'DisplayPort'], TRUE),
  ('Memorie Forge Pulse 16 GB', 'Kit de memorie pentru sisteme de birou si gaming accesibil.', '/resurse/imagini/galerie/originale/module-memorie.jpg', 'componente', 'memorie-ram', 229.90, 67, '2026-01-22', 'negru', ARRAY['DDR4'], TRUE),
  ('Memorie Forge Pulse 32 GB', 'Kit dual-channel pentru multitasking, jocuri si aplicatii solicitante.', '/resurse/imagini/galerie/originale/module-memorie.jpg', 'componente', 'memorie-ram', 449.90, 84, '2026-05-28', 'negru', ARRAY['DDR5', 'XMP'], TRUE),
  ('Carcasa Forge Airflow', 'Carcasa ATX cu panou lateral transparent si traseu optimizat al aerului.', '/resurse/imagini/galerie/originale/carcasa-pc.jpg', 'componente', 'carcasa', 389.00, 79, '2026-02-06', 'negru', ARRAY['USB-C', 'USB-A', 'Audio'], TRUE),
  ('SSD Forge Sprint 512 GB', 'Unitate rapida pentru sistemul de operare si aplicatiile folosite zilnic.', '/resurse/imagini/galerie/originale/ssd-msata.jpg', 'stocare', 'ssd', 219.50, 72, '2026-04-03', 'negru', ARRAY['mSATA'], TRUE),
  ('SSD Forge Sprint 1 TB', 'Spatiu generos si timpi de incarcare redusi pentru jocuri si proiecte.', '/resurse/imagini/galerie/originale/ssd-msata.jpg', 'stocare', 'ssd', 399.90, 86, '2026-05-17', 'negru', ARRAY['NVMe', 'PCIe'], TRUE),
  ('SSD Forge Archive 2 TB', 'Unitate pentru biblioteci media, proiecte si copii de siguranta rapide.', '/resurse/imagini/galerie/originale/ssd-msata.jpg', 'stocare', 'ssd', 699.00, 90, '2025-12-08', 'negru', ARRAY['NVMe', 'PCIe'], FALSE),
  ('Cooler Forge Frost 120', 'Răcire compactă pentru procesoare eficiente și configurații silențioase.', '/resurse/imagini/galerie/originale/cooler-procesor.png', 'racire', 'cooler-procesor', 159.90, 64, '2026-03-02', 'argintiu', ARRAY['PWM', '4-pin'], TRUE),
  ('Cooler Forge Frost Pro', 'Radiator extins si ventilator PWM pentru sarcini sustinute.', '/resurse/imagini/galerie/originale/cooler-procesor.png', 'racire', 'cooler-procesor', 289.00, 83, '2026-05-26', 'negru', ARRAY['PWM', 'ARGB', '4-pin'], TRUE),
  ('Set ventilatoare Forge Flow', 'Trei ventilatoare pentru admisie si evacuare controlata a aerului.', '/resurse/imagini/galerie/originale/ventilatoare-carcasa.jpg', 'racire', 'ventilator', 179.90, 71, '2026-02-25', 'negru', ARRAY['PWM', 'ARGB'], TRUE),
  ('Tastatura Forge Command', 'Tastatura completa pentru lucru, studiu si control precis in jocuri.', '/resurse/imagini/galerie/originale/tastatura.jpg', 'periferice', 'tastatura', 249.00, 73, '2026-04-27', 'negru', ARRAY['USB-A'], TRUE),
  ('Tastatura Forge Command Wireless', 'Model fara fir, compact si potrivit pentru un birou ordonat.', '/resurse/imagini/galerie/originale/tastatura.jpg', 'periferice', 'tastatura', 349.90, 78, '2026-05-30', 'alb', ARRAY['Bluetooth', 'USB-C'], TRUE),
  ('Mouse Forge Vector', 'Mouse optic ergonomic pentru navigare si sesiuni lungi de lucru.', '/resurse/imagini/galerie/originale/mouse.jpg', 'periferice', 'mouse', 129.90, 69, '2026-01-16', 'negru', ARRAY['USB-A'], TRUE),
  ('Mouse Forge Vector Air', 'Mouse wireless usor, cu sensibilitate reglabila si autonomie extinsa.', '/resurse/imagini/galerie/originale/mouse.jpg', 'periferice', 'mouse', 219.90, 81, '2026-05-24', 'alb', ARRAY['Bluetooth', 'USB-C', 'Wireless'], FALSE),
  ('Monitor Forge View 24', 'Monitor Full HD pentru birou, invatare si divertisment.', '/resurse/imagini/galerie/originale/monitor.jpg', 'monitoare', 'monitor', 649.90, 74, '2026-03-20', 'negru', ARRAY['HDMI', 'DisplayPort'], TRUE),
  ('Monitor Forge View 27', 'Panou generos cu rezolutie ridicata pentru creatie si gaming.', '/resurse/imagini/galerie/originale/monitor.jpg', 'monitoare', 'monitor', 1199.90, 89, '2026-05-29', 'gri', ARRAY['HDMI', 'DisplayPort', 'USB-C'], TRUE);
