"""Generează versiunea narativă a ghidului de prezentare PC Forge.

Documentul este intenționat explicativ: fiecare cerință este tratată separat,
în limbaj accesibil unui student care trebuie să susțină proiectul oral.
"""

from pathlib import Path
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Inches, Pt

import genereaza_ghid_prezentare as base


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "documentatie" / "Ghid_prezentare_PC_Forge_Etapele_5_8_si_10.docx"


def p(doc, label, text):
    """Adaugă un paragraf explicativ cu etichetă vizibilă."""
    return base.add_para(doc, f"{label} {text}", bold_prefix=f"{label} ", after=8, keep=True)


def requirement(doc, title, cerinta, implementare, explicatie, prezentare, fisiere, cod=None):
    base.add_heading(doc, title, 2)
    p(doc, "Ce cere cerința:", cerinta)
    p(doc, "Ce am implementat:", implementare)
    p(doc, "Cum trebuie să înțelegi mecanismul:", explicatie)
    if cod:
        base.add_code(doc, cod)
    p(doc, "Unde găsești implementarea:", fisiere)
    base.add_callout(doc, "Ce poți spune la prezentare:", prezentare)


def bonus(doc, number, title, points, cerinta, implementare, explicatie, prezentare, fisiere, status="implementat"):
    suffix = f" ({points})" if points else ""
    base.add_heading(doc, f"Bonus {number} - {title}{suffix}", 2)
    p(doc, "Ce cere bonusul:", cerinta)
    p(doc, "Ce am făcut:", implementare)
    p(doc, "Ideea tehnică, explicată simplu:", explicatie)
    p(doc, "Starea în proiect:", status)
    p(doc, "Fișiere importante:", fisiere)
    base.add_callout(doc, "Formulare pentru profesoară:", prezentare)


def configure_narrative_style(doc):
    """Aplică presetul narrative_proposal, adaptat cromatic PC Forge."""
    normal = doc.styles["Normal"]
    normal.paragraph_format.space_after = Pt(8)
    normal.paragraph_format.line_spacing = 1.333
    heading_specs = {
        "Heading 1": (16, 18, 10),
        "Heading 2": (13, 12, 6),
        "Heading 3": (12, 8, 4),
    }
    for name, (size, before, after) in heading_specs.items():
        style = doc.styles[name]
        style.font.size = Pt(size)
        style.paragraph_format.space_before = Pt(before)
        style.paragraph_format.space_after = Pt(after)
    for section in doc.sections:
        section.page_width = Inches(8.5)
        section.page_height = Inches(11)
        section.top_margin = Inches(1)
        section.bottom_margin = Inches(1)
        section.left_margin = Inches(1)
        section.right_margin = Inches(1)
        section.header_distance = Inches(0.492)
        section.footer_distance = Inches(0.492)


def add_cover(doc):
    lead = doc.add_paragraph()
    lead.paragraph_format.space_before = Pt(105)
    lead.paragraph_format.space_after = Pt(16)
    lead.alignment = WD_ALIGN_PARAGRAPH.CENTER
    base.set_font(lead.add_run("MANUAL DE ÎNȚELEGERE ȘI PREZENTARE"), size=11, color=base.RED, bold=True)

    title = doc.add_paragraph()
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    title.paragraph_format.space_after = Pt(10)
    base.set_font(title.add_run("PC Forge"), size=32, color=base.DARK, bold=True)

    subtitle = doc.add_paragraph()
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    subtitle.paragraph_format.space_after = Pt(26)
    base.set_font(subtitle.add_run("Etapele 5, 6, 7, 8 și 10, explicate cerință cu cerință"), size=15, color=base.GRAY)

    author = doc.add_paragraph()
    author.alignment = WD_ALIGN_PARAGRAPH.CENTER
    author.paragraph_format.space_before = Pt(55)
    base.set_font(author.add_run("Popa Bogdan"), size=12, color=base.DARK, bold=True)

    base.add_callout(
        doc,
        "Cum a fost gândit acest ghid:",
        "Nu este o listă de definiții de memorat. Fiecare subcapitol pornește de la cerință, urmărește traseul datelor prin aplicație și se încheie cu o formulare pe care o poți folosi la prezentare.",
    )
    doc.add_page_break()


def add_intro(doc):
    base.add_heading(doc, "Cum să înveți din acest document", 1)
    base.add_para(doc, "Încearcă să nu memorezi propozițiile exact. Pentru fiecare cerință trebuie să poți răspunde la patru întrebări: ce problemă rezolvă, unde se află codul, cum circulă informația și ce vede utilizatorul la final. Dacă poți explica aceste patru lucruri cu propriile cuvinte, înseamnă că ai înțeles implementarea.")
    base.add_para(doc, "Când întâlnești un termen precum middleware, sesiune, query parametrizat sau pseudo-element, citește mai întâi explicația simplă. Apoi deschide fișierul indicat și caută comentariul cu etapa și taskul. Comentariile din proiect au fost păstrate tocmai pentru ca tu și profesoara să puteți identifica rapid cerința.")
    base.add_callout(doc, "Model de răspuns bun:", "«Cerința urmărește X. În proiect am implementat-o în fișierul Y. Datele pornesc din Z, sunt prelucrate de funcția W și rezultatul este afișat astfel. Am ales soluția aceasta deoarece...»")


def add_stage5(doc):
    doc.add_page_break()
    base.add_heading(doc, "Etapa 5 - SCSS, Bootstrap personalizat, galerii și efecte CSS", 1)
    base.add_para(doc, "În această etapă site-ul trece de la CSS scris numai manual la un sistem în care stilurile pot fi generate. În paralel, pagina primește galerii construite din date și efecte CSS care demonstrează utilizarea pseudo-elementelor, animațiilor și proprietăților responsive.")

    requirement(doc, "5.1 Galeria statică", "Serverul trebuie să citească un fișier JSON cu imagini și să trimită către pagină numai imaginile potrivite momentului curent. Galeria trebuie să fie generată prin EJS și să își schimbe numărul de coloane în funcție de lățimea ecranului.", "Fișierul galerie.json conține calea comună și obiectele imaginilor. index.js citește datele, determină sfertul orei și selectează imaginile corespunzătoare. Fragmentul galerie-statica.ejs parcurge vectorul primit și produce elementele HTML, iar galerie.scss generează regulile de grid.", "JSON-ul păstrează date, nu aspect. Serverul transformă textul JSON într-un obiect JavaScript, filtrează vectorul și transmite rezultatul către EJS. EJS rulează pe server și construiește HTML înainte ca pagina să ajungă în browser. CSS Grid decide apoi poziția imaginilor. Această separare este importantă: datele, logica și prezentarea nu sunt amestecate.", "Am separat metadatele imaginilor de HTML. Serverul decide ce imagini sunt relevante, EJS le afișează, iar gridul SCSS adaptează galeria la ecran. Dacă schimb JSON-ul, nu trebuie să rescriu structura paginii.", "resurse/json/galerie.json, index.js, views/fragmente/galerie-statica.ejs și resurse/sass/galerie.scss")

    requirement(doc, "5.2 Compilarea automată SCSS", "Toate fișierele SCSS trebuie compilate la pornirea serverului, iar modificările ulterioare trebuie urmărite automat. Înainte de suprascrierea CSS-ului vechi trebuie creat un backup.", "În index.js există căile globale pentru folderele SCSS și CSS și funcția compileazaScss(). La pornire, serverul parcurge sursele și le compilează cu pachetul sass. fs.watch urmărește modificările, iar înainte de compilare versiunea CSS existentă este copiată în backup/resurse/css.", "SCSS nu este înțeles direct de browser. El este o sursă mai puternică, ce permite variabile și bucle, dar trebuie transformat în CSS. fs.watch este un observator al sistemului de fișiere: când primește un eveniment de modificare, reapelăm compilarea doar pentru fișierul afectat. Backupul este creat înainte de suprascriere, ca versiunea anterioară să poată fi recuperată.", "Browserul citește CSS, nu SCSS. De aceea serverul automatizează transformarea. La pornire compilez toate fișierele, apoi urmăresc schimbările cu fs.watch și salvez CSS-ul vechi înainte de a-l înlocui.", "index.js, resurse/sass și resurse/css", "compileazaScss(caleScss, caleCss)\nfs.watch(folderScss, ..., numeFisier => compileazaScss(numeFisier))")

    requirement(doc, "5.3 Bootstrap personalizat prin Sass", "Bootstrap trebuie importat în SCSS după suprascrierea variabilelor sale: culori, font, raze, headinguri și breakpointuri. Trebuie folosite și componente care demonstrează tema personalizată.", "custom-bootstrap.scss definește variabilele înainte de importul Bootstrap. Secțiunea #bootstrap-custom folosește carduri, grid, butoane și alertă cu informații reale despre PC Forge. CSS-ul Bootstrap este încărcat înaintea stilurilor proprii, astfel încât regulile site-ului pot corecta conflictele.", "Sass evaluează variabilele înainte să genereze CSS. Dacă variabila Bootstrap pentru primary devine roșul PC Forge, toate clasele care depind de primary sunt generate cu această culoare. btn-primary și btn-outline-primary sunt două stări intenționat diferite: primul este plin, al doilea este doar conturat până la hover. Nu este o eroare, ci comportamentul Bootstrap.", "Am recompilat Bootstrap cu identitatea PC Forge. Nu am colorat manual fiecare buton; am schimbat variabilele sursă, iar componentele Bootstrap au moștenit tema. Cardurile prezintă funcții reale ale proiectului, nu text placeholder.", "resurse/sass/custom-bootstrap.scss, resurse/css/custom-bootstrap.css și views/pagini/index.ejs")

    requirement(doc, "5.4 Efectul duotone", "O imagine trebuie afișată cu două culori și trebuie să treacă treptat în grayscale la hover folosind pseudo-elemente și mix-blend-mode.", "Containerul imaginii creează două straturi prin ::before și ::after. Straturile folosesc culorile temei, iar mix-blend-mode combină matematic culoarea cu imaginea. La hover se modifică filtrul și opacitatea printr-o tranziție.", "Pseudo-elementele sunt elemente vizuale generate de CSS, fără taguri suplimentare în HTML. mix-blend-mode stabilește cum se combină pixelii stratului superior cu cei ai imaginii. filter: grayscale(1) elimină saturația, iar transition face schimbarea progresivă, nu instantanee.", "Efectul nu modifică fișierul imaginii. Browserul suprapune două straturi colorate și calculează amestecul; la hover animă filtrul spre grayscale.", "views/pagini/index.ejs și resurse/css/stil.css")

    requirement(doc, "5.5 Reflexia textului", "Un heading trebuie să aibă o reflexie portabilă, vizibilă în browsere moderne, blurată și alungită când utilizatorul trece cu mouse-ul.", "Textul este duplicat într-un pseudo-element poziționat sub elementul original. Reflexia este răsturnată vertical cu transform: scaleY(-1), estompată cu opacity și filter: blur(), iar hoverul modifică transformarea și blurul.", "O reflexie reală nu necesită o a doua etichetă scrisă manual. Pseudo-elementul folosește content pentru a repeta textul, transformarea îl răstoarnă, iar originea transformării stabilește punctul din care pare că se întinde. Tranziția interpolează valorile dintre starea normală și hover.", "Am evitat o proprietate dependentă de un singur motor de browser. Reflexia este construită din pseudo-element, transformare, opacitate și blur, proprietăți standard și ușor de explicat.", "views/pagini/index.ejs și resurse/css/stil.css")

    requirement(doc, "5.6 Selecția personalizată, HR-ul și textul animat", "Etapa cere efecte CSS suplimentare care să demonstreze pseudo-elemente, animații și adaptarea la schema cromatică.", "::selection schimbă fundalul și culoarea textului selectat. HR-ul este redesenat prin gradient și pseudo-elemente. Textul animat se află într-un container cu overflow: hidden și se deplasează prin @keyframes fără să creeze scroll orizontal.", "::selection se aplică doar zonei selectate cu mouse-ul. overflow: hidden taie partea textului care iese din container, iar white-space: nowrap îl ține pe un singur rând. În animație, transform: translateX() mută elementul fără să recalculeze întregul layout, ceea ce este mai eficient decât modificarea continuă a marginilor.", "Am folosit efecte care rămân în tema site-ului și au un scop vizibil. La textul animat, containerul ascunde partea din afara lui, deci animația nu lărgește pagina și nu produce scrollbar.", "resurse/css/stil.css și views/pagini/index.ejs")

    bonus(doc, "1", "Galeria animată", "0,5 p", "Se cere o galerie cu un număr aleator de imagini, divizibil cu trei, imagini distincte și consecutive în JSON. Animația trebuie generată cu Sass și oprită la hover.", "Serverul alege la fiecare pornire numărul și offsetul, iar fragmentul galerie-animata.ejs primește imaginile. galerie.scss generează pozițiile animației în funcție de numărul real de elemente. Ultima imagine este urmată de prima pentru o buclă fără salt vizibil.", "Numărul aleator este calculat pe server, pentru ca HTML-ul să conțină exact imaginile selectate. Sass generează procentele keyframe-urilor. animation-play-state: paused oprește timpul animației când cursorul este peste galerie.", "Galeria nu este o listă fixă. Numărul și poziția de pornire se aleg prin program, iar Sass produce animația potrivită structurii primite.", "index.js, views/fragmente/galerie-animata.ejs și resurse/sass/galerie.scss")

    bonus(doc, "3-5", "Backup cu timestamp, nume cu puncte și validarea galeriei", "0,125 p", "Backupurile trebuie să păstreze mai multe versiuni, compilarea să accepte nume cu mai multe puncte, iar datele galeriei să fie validate la pornire.", "Numele backupului include Date.now(). Extensia este determinată cu path.parse(), nu printr-un split fragil. valideazaGalerie() verifică existența folderului cale_galerie și a fiecărei imagini înainte ca serverul să deservească pagini.", "Un timestamp este un număr care identifică momentul salvării, deci două backupuri nu se suprascriu. path.parse separă corect numele, extensia și folderul chiar pentru stil.frumos.scss. Validarea timpurie mută eroarea la pornire, unde este ușor de diagnosticat, în loc să lase imagini lipsă în pagină.", "Am tratat și cazurile-limită: păstrez versiuni multiple, nu presupun că numele are un singur punct și opresc problema din timp prin validarea tuturor căilor galeriei.", "index.js și resurse/json/galerie.json")


def add_stage6(doc):
    doc.add_page_break()
    base.add_heading(doc, "Etapa 6 - PostgreSQL și pagina dinamică de produse", 1)
    base.add_para(doc, "Etapa 6 este nucleul catalogului PC Forge. Produsele nu mai sunt scrise în HTML, ci sunt înregistrări PostgreSQL. Serverul le citește, EJS generează cardurile, iar JavaScript oferă filtrare, sortare și calcule fără să recreeze inutil pagina.")

    requirement(doc, "6.1 Baza de date și tabela produse", "Trebuie creată o bază separată pentru proiect, un utilizator limitat al aplicației și o tabelă cu minimum 15-20 de produse și caracteristici variate.", "compose.yaml pornește PostgreSQL într-un container separat de baza lucrării de licență. Fișierele database/01-schema.sql și 02-data.sql creează tipurile ENUM, tabela produse și datele PC Forge. 03-permissions.sh configurează utilizatorul aplicației cu drepturile necesare.", "Containerul izolează serviciul și păstrează datele într-un volum. ENUM limitează câmpul la valori cunoscute, de exemplu categoria. Utilizatorul aplicației nu este superuser; primește numai permisiunile necesare, ceea ce reduce efectele unei eventuale erori.", "Am creat o bază distinctă pentru site, nu am reutilizat baza licenței. Schema validează tipurile de date, iar aplicația se conectează cu un utilizator cu privilegii limitate.", "compose.yaml, database/01-schema.sql, database/02-data.sql și database/03-permissions.sh")

    requirement(doc, "6.2 Afișarea produselor și pagina unui produs", "Serverul trebuie să listeze produsele relevante și să ofere o pagină separată pentru fiecare produs, transmisă prin id.", "Ruta /produse citește produsele prin modulul acces-produse și transmite vectorul către produse.ejs. Ruta /produs/:id extrage id-ul din URL, îl validează și caută exact produsul. Dacă id-ul nu există, răspunsul folosește pagina de eroare.", "Parametrul :id este o valoare variabilă din URL. Query-ul folosește $1 și trimite id-ul separat, deci textul introdus de utilizator nu devine SQL. EJS primește un obiect produs și poate afișa fiecare proprietate fără cod HTML duplicat pentru fiecare produs.", "Lista și pagina individuală folosesc aceeași sursă PostgreSQL. Id-ul din URL este validat și trimis ca parametru separat către query, ceea ce protejează interogarea.", "index.js, module/acces-produse.js, views/pagini/produse.ejs și views/pagini/produs.ejs")

    requirement(doc, "6.3 Formatarea fiecărui produs", "Fiecare produs trebuie afișat într-un articol cu heading, tabel de caracteristici, dată în tagul time, imagine și clase care includ categoria.", "EJS generează article cu id de forma elem-ID și clase pentru categorie/subcategorie. Caracteristicile sunt într-un tabel compact, data este în time, imaginea are cale din bază, iar prețul și descrierea sunt afișate separat.", "Clasele și atributele data-* au două roluri: CSS le poate stiliza, iar JavaScript poate citi valorile prin dataset. Tagul time oferă o valoare semantică pentru dată. hidden ascunde produsul fără să îl șteargă din DOM, astfel încât poate reapărea la resetare.", "Am păstrat în DOM toate informațiile necesare filtrării. Produsul este generat semantic de EJS, iar JavaScript îl poate ascunde și readuce fără o cerere nouă.", "views/pagini/produse.ejs și resurse/js/produse.js")

    requirement(doc, "6.4 Cele opt filtre", "Deasupra listei trebuie să existe opt tipuri distincte de input și fiecare să filtreze după o caracteristică relevantă.", "Pagina folosește text pentru nume, range pentru scor, datalist pentru culoare, radio pentru stoc, checkboxuri pentru categorii, textarea pentru descriere, select simplu pentru subcategorie și select multiplu pentru conectivitate. aplicaFiltrare() citește toate valorile și decide pentru fiecare card dacă rămâne vizibil.", "Fiecare filtru produce o condiție booleană. Cardul este vizibil numai dacă toate condițiile active sunt adevărate. Pentru selectul multiplu se folosește every(), fiindcă produsul trebuie să conțină toate opțiunile selectate. Filtrele necompletate sunt tratate ca «nu mă interesează».", "Am ales opt controale diferite, dar toate ajung într-o singură funcție. Funcția construiește condițiile și setează proprietatea hidden; nu șterge cardurile, ca ele să poată reveni.", "views/pagini/produse.ejs și resurse/js/produse.js")

    requirement(doc, "6.5 Validarea filtrelor", "Operațiile de filtrare, sortare și calcul trebuie executate numai când valorile afectate sunt valide.", "valideazaInputuri() verifică expresia pentru nume, lungimea textarea și apartenența culorii la opțiunile valide. setCustomValidity() setează mesajul nativ, clasele Bootstrap oferă semnal vizual, iar reportValidity() afișează explicația când utilizatorul cere operația.", "Validarea în client nu protejează baza, dar previne rezultate confuze și oferă feedback rapid. setCustomValidity nu este doar o culoare CSS; schimbă starea reală de validitate a controlului. Când valoarea devine corectă, mesajul este golit și controlul revine automat la starea validă.", "Înainte de operație verific inputurile. Dacă o valoare este greșită, nu continui cu un rezultat incorect, ci folosesc mecanismul nativ al browserului și stilul Bootstrap pentru explicație.", "resurse/js/produse.js și views/pagini/produse.ejs")

    requirement(doc, "6.6 Sortarea după două chei", "Utilizatorul trebuie să poată sorta crescător și descrescător după două caracteristici, cu o a doua cheie folosită la egalitate.", "Două selecturi aleg cheile. sorteazaProduse() copiază cardurile vizibile, compară prima proprietate și, dacă rezultatul este zero, compară proprietatea secundară. Direcția se aplică prin înmulțire cu 1 sau -1, apoi append mută cardurile în ordinea nouă.", "Comparatorul trebuie să întoarcă un număr negativ, zero sau pozitiv. Zero înseamnă egalitate după prima cheie, deci este momentul pentru cheia a doua. append nu creează duplicate: când primește un element deja existent, îl mută în noua poziție.", "Am un comparator cu două niveluri. Cheia secundară este folosită numai la egalitate, iar aceeași funcție servește ambele sensuri prin factorul 1 sau -1.", "resurse/js/produse.js")

    requirement(doc, "6.7 Calcularea prețurilor vizibile", "Trebuie calculată suma, media, minimul sau maximul pentru produsele rămase după filtrare, iar rezultatul să apară temporar într-un element creat dinamic.", "calculeazaPreturi() selectează cardurile neascunse, transformă prețurile în numere și aplică operația aleasă. Rezultatul este introdus într-un div creat cu document.createElement(), fixat pe ecran și eliminat după două secunde cu setTimeout().", "Calculul lucrează asupra stării curente a interfeței, nu asupra tuturor produselor. map extrage numerele, reduce însumează, iar Math.min/Math.max tratează extremele. Elementul nu există inițial în HTML, ceea ce demonstrează creare și ștergere din DOM.", "Calculez numai produsele vizibile după filtrare. Mesajul rezultat este creat prin JavaScript, rămâne două secunde și este eliminat complet, exact cum cere enunțul.", "resurse/js/produse.js")

    requirement(doc, "6.8 Resetarea", "Resetarea trebuie confirmată și trebuie să refacă valorile inițiale, toate produsele și ordinea originală.", "reseteazaFiltre() folosește confirm(), reface valorile implicite, golește mesajele de validare, șterge filtrele persistente și sortează cardurile după data-index-initial memorată la încărcare.", "Resetarea nu înseamnă doar golirea inputurilor. Trebuie refăcută și starea ascunsă, sortarea și opțiunea de persistență. data-index-initial este o copie a poziției primite de la server, folosită ca reper stabil.", "Am memorat ordinea inițială în fiecare card. După confirmare refac inputurile, vizibilitatea și ordinea, fără să reîncarc pagina.", "resurse/js/produse.js")

    requirement(doc, "6.9 Bootstrap aplicat controalelor", "Butoanele și inputurile trebuie stilizate cu Bootstrap personalizat, așezate într-un grid responsive, cu iconuri și adaptare pentru ecrane mici.", "Formularul folosește row, col-* și clasele form-control, form-select, btn, btn-check și form-range. Butoanele au Bootstrap Icons, iar textul lor se ascunde pe ecran mic, lăsând iconul. Variabilele Sass controlează raza, bordura și dimensiunea thumb-ului range.", "Clasele Bootstrap descriu comportamentul, iar CSS-ul generat din custom.scss îi dă identitatea PC Forge. Gridul Bootstrap nu este același lucru cu CSS Grid-ul galeriei: aici coloanele responsive sunt obținute prin clase prestabilite și breakpointuri.", "Nu am reprodus manual componentele Bootstrap. Am folosit clasele lor pentru accesibilitate și responsive, apoi am personalizat variabilele Sass pentru culoare, rază și inputul range.", "views/pagini/produse.ejs și resurse/sass/custom.scss")

    requirement(doc, "6.10 Tema globală", "Site-ul trebuie să ofere light/dark, să rețină alegerea și să o aplice pe toate paginile.", "tema.js citește alegerea, setează atributul data-tema pe elementul html și salvează cheia în localStorage. Selectorul este în headerul comun, deci apare pe toate paginile. CSS schimbă variabilele de suprafață, text și umbră.", "localStorage este memorie a browserului asociată domeniului. El păstrează un text după refresh, dar nu este trimis automat serverului. data-tema este un comutator pentru selectori precum html[data-tema='dark']; astfel o singură valoare activează un întreg set de variabile CSS.", "Salvez doar numele temei. Atributul data-tema activează variabilele CSS, iar pentru că selectorul și scriptul sunt în fragmente comune, tema este globală.", "views/fragmente/header.ejs, resurse/js/tema.js și resurse/sass/produse.scss")

    bonuses = [
        ("1", "Valori și opțiuni generate din date", "maxim 0,8 p", "Valorile min/max și opțiunile inputurilor trebuie deduse din produsele reale.", "Serverul calculează limitele și listele distincte înainte de randarea paginii.", "Interfața rămâne corectă dacă datele din bază se schimbă; nu există valori copiate manual.", "Am generat atributele din datele PostgreSQL, deci formularul descrie catalogul real.", "module/acces-produse.js, index.js, views/pagini/produse.ejs", "implementat"),
        ("2", "A treia temă", "0,15 p", "Trebuie minimum trei teme persistente.", "Am adăugat Contrast Forge pe lângă light și dark.", "Aceeași cheie de temă poate avea trei valori; CSS are selectori separați pentru contrast.", "Tema a treia nu este un simplu buton colorat, ci un set complet de variabile cu contrast crescut.", "resurse/js/tema.js și resurse/sass/produse.scss", "implementat"),
        ("3", "Mesaj fără rezultate", "0,05 p", "Lista goală trebuie explicată utilizatorului.", "După filtrare este numărat rezultatul; mesajul dedicat este afișat când numărul este zero.", "O interfață goală pare o eroare, pe când mesajul confirmă că filtrarea a funcționat.", "Verific numărul cardurilor vizibile și afișez explicit starea fără rezultate.", "resurse/js/produse.js și views/pagini/produse.ejs", "implementat"),
        ("4", "Filtrare imediată", "maxim 0,4 p", "Cele opt filtre trebuie să reacționeze la input/change.", "Ascultătorii de eveniment reaplică funcția comună fără click pe buton.", "Evenimentul input este potrivit pentru text și range, iar change pentru select, radio și checkbox.", "Toate controalele folosesc aceeași logică; diferă doar momentul în care o declanșează.", "resurse/js/produse.js", "implementat pentru toate cele opt filtre"),
        ("5", "Paginare", "0,5 p", "Trebuie afișate K produse și generate ceil(N/K) controale de pagină.", "K este 6, iar butoanele sunt reconstruite după filtrare. Pagina curentă decide intervalul vizibil.", "Pentru pagina P, indicii încep la (P-1)*K. Filtrarea și paginarea sunt combinate, ca produsele eliminate să nu ocupe locuri.", "Am 20 de produse și șase pe pagină, deci sunt generate automat patru pagini.", "resurse/js/produse.js", "implementat"),
        ("6", "Fixare și două tipuri de ascundere", "0,5 p", "Fiecare card primește trei butoane cu comportamente diferite.", "Primul fixează cardul peste filtre, al doilea îl ascunde temporar, iar al treilea salvează ascunderea în sessionStorage.", "sessionStorage supraviețuiește refreshului doar în tabul curent. Fixarea este o excepție evaluată înaintea condițiilor de filtrare.", "Am separat o acțiune de moment, o excepție de filtrare și o stare persistentă numai în tab.", "resurse/js/produse.js și views/pagini/produse.ejs", "implementat"),
        ("7", "Echivalarea diacriticelor", "0,15 p", "Căutarea trebuie să considere ș și s echivalente.", "normalize('NFD') separă diacritica, iar expresia regulată elimină semnele combinatorii.", "Normalizăm ambele texte înainte de includes; originalul afișat nu este modificat.", "Caut în forma normalizată, dar păstrez în pagină scrierea românească originală.", "resurse/js/produse.js", "implementat"),
        ("8", "Chei de sortare alese", "0,35 p", "Utilizatorul alege două chei din minimum trei.", "Cele două selecturi alimentează comparatorul cu două niveluri.", "Funcția este generală: nu există un comparator separat pentru fiecare combinație.", "Utilizatorul controlează ambele criterii și sensul; cheia a doua rezolvă egalitatea.", "resurse/js/produse.js", "implementat"),
        ("9", "Imagini multiple", "0,5 p", "Pagina produsului trebuie să permită schimbarea imaginii.", "Este folosit un carusel Bootstrap care include imaginea principală și imagini asociate din catalog.", "Caruselul schimbă slide-ul cu JavaScript Bootstrap și păstrează o singură zonă vizuală.", "Am integrat componenta carousel pe pagina produsului și o alimentez din datele trimise de server.", "views/pagini/produs.ejs și index.js", "implementat funcțional; imaginile suplimentare sunt asociate din catalog, nu stocate într-un tabel separat per produs"),
        ("10", "Filtrare și sortare pe server cu fetch", "0,6 p", "Aceleași operații trebuie executate și pe server, iar bonusul fetch evită reîncărcarea completă.", "Endpointul /api/produse-filtrate primește parametrii, construiește query parametrizat și răspunde JSON. Browserul actualizează rezultatul după fetch.", "Clientul trimite doar criteriile; baza selectează și ordonează. JSON este formatul de schimb dintre server și JavaScript.", "Pot demonstra două niveluri: filtrarea rapidă locală și filtrarea reală în PostgreSQL printr-un endpoint fetch.", "index.js, module/acces-produse.js și resurse/js/produse.js", "implementat"),
        ("11", "Modal Bootstrap", "0,4 p", "Clickul pe card trebuie să deschidă informațiile într-un modal.", "Un modal Bootstrap reutilizabil este populat cu dataset-ul cardului și poate fi închis prin controalele standard.", "Nu generăm câte un modal pentru fiecare produs; refolosim unul și îi schimbăm conținutul.", "Am folosit componenta JavaScript Bootstrap și am separat clickul pe butoane de clickul pe card.", "views/pagini/produse.ejs și resurse/js/produse.js", "implementat"),
        ("12", "Oferte periodice", "1,2 p", "Oferta trebuie generată periodic, salvată în JSON, afișată cu timer și aplicată prețurilor.", "oferte.js alege categoria și reducerea, evită repetarea categoriei, scrie oferte.json și calculează prețul redus. Prima pagină are anunț și countdown; produsele din categorie afișează preț vechi și nou.", "Serverul este sursa de adevăr pentru ofertă, iar browserul scade secundele doar pentru afișaj. La expirare, datele sunt regenerate.", "Oferta nu este un text fix: are categorie din bază, interval, procent, temporizator și efect real asupra prețurilor.", "module/oferte.js, resurse/json/oferte.json și resurse/js/oferte.js", "implementat"),
        ("13", "Ștergerea backupurilor vechi", "0,15 p", "Un interval trebuie să șteargă fișierele de backup mai vechi decât T.", "Nu am activat și nu am adăugat ștergerea automată fără o perioadă de păstrare aprobată.", "Ștergerea este ireversibilă; trebuie stabilită întâi politica și testată pe un folder controlat.", "Acest bonus este singurul din Etapa 6 pe care nu îl prezint ca implementat, pentru a nu pretinde o operație distructivă inexistentă.", "nu există rută activă; backupurile sunt create în backup/resurse/css", "neimplementat deliberat"),
        ("14", "Cel mai ieftin pe categorie", "0,3 p", "Trebuie marcat produsul cu preț minim din fiecare categorie.", "Serverul calculează MIN(preț) grupat pe categorie și adaugă un badge cardurilor corespunzătoare.", "GROUP BY împarte produsele pe categorii, iar MIN extrage extrema fiecărui grup.", "Marcajul este calculat din bază, nu scris manual pe produse alese.", "module/acces-produse.js și views/pagini/produse.ejs", "implementat"),
        ("15", "Numărul produselor vizibile", "0,05 p", "Contorul trebuie actualizat după fiecare filtrare.", "Funcția comună numără cardurile care corespund înainte de paginare și actualizează textul.", "Contorul descrie rezultatul filtrării, nu doar cele șase carduri din pagina curentă.", "Actualizez contorul în același loc în care actualizez vizibilitatea, evitând valori rămase în urmă.", "resurse/js/produse.js", "implementat"),
        ("16", "Produse similare", "0,3 p", "Pagina unui produs trebuie să recomande articole după un criteriu calculat.", "Query-ul caută aceeași categorie/subcategorie și apropie prețul, excluzând produsul curent.", "Similitudinea este o regulă explicită în SQL; LIMIT controlează câte rezultate apar.", "Nu am ales manual recomandările. Baza le calculează în raport cu produsul deschis.", "module/acces-produse.js și views/pagini/produs.ejs", "implementat"),
        ("17", "Seturi de produse", "1 p", "Trebuie tabele de seturi și asociere, minimum cinci seturi, pagină dedicată și preț redus calculat.", "Migrarea creează seturi și asociere_set. /seturi listează seturile, iar pagina produsului arată apartenența. Prețul este suma minus min(5,n)*5%.", "Relația many-to-many înseamnă că un set conține mai multe produse și același produs poate fi în mai multe seturi; tabela de legătură păstrează perechile.", "Am modelat relația corect în baza de date și calculez reducerea din numărul produselor, nu o salvez arbitrar.", "database/06-bonusuri-etapele6-8.sql, index.js, views/pagini/seturi.ejs", "implementat"),
        ("18", "Produse noi", "0,2 p", "Produsele recente trebuie marcate și promovate pe prima pagină.", "Serverul compară data_adaugare cu un interval configurat, adaugă badge NOU și selectează cele mai recente produse pentru fragmentul de homepage.", "Starea «nou» este derivată din dată, deci dispare automat după interval.", "Nu există o listă manuală de produse noi; timpul curent și data din bază decid marcajul.", "module/acces-orm.js, views/fragmente/produse-noi.ejs și views/pagini/produse.ejs", "implementat"),
        ("19", "Orarul global", "0,2 p", "Orarul trebuie accesibil pe orice pagină și să indice deschis/închis.", "orar.ejs este fragment comun, orar.js marchează ziua și compară ora curentă cu intervalul. Panoul fix se deschide și se închide fără navigare.", "Ora este transformată în minute pentru o comparație simplă. Fragmentul elimină duplicarea HTML-ului.", "Orarul este o componentă globală; starea firmei se calculează, nu este un text fix.", "views/fragmente/orar.ejs și resurse/js/orar.js", "implementat"),
        ("20", "Compararea a două produse", "1,5 p", "Două produse trebuie selectate persistent, eliminate individual și afișate paralel într-o fereastră nouă.", "localStorage păstrează id-urile și ultimul moment de interacțiune pentru o zi. Containerul fix apare pe paginile de produse, butoanele se dezactivează la două selecții, iar /comparare afișează caracteristicile pe coloane.", "Persistența este potrivită fiindcă lista trebuie să supraviețuiască închiderii paginii. Serverul primește id-urile și citește obiectele reale din bază.", "Starea comparării persistă o zi, poate fi corectată prin ștergere și produce o pagină paralelă din datele PostgreSQL.", "resurse/js/produse.js, index.js și views/pagini/comparare.ejs", "implementat"),
    ]
    for item in bonuses:
        bonus(doc, *item)


def add_stage7(doc):
    doc.add_page_break()
    base.add_heading(doc, "Etapa 7 - Bootstrap JavaScript, cookie-uri și arhitectura utilizatorilor", 1)
    base.add_para(doc, "Etapa 7 introduce două tipuri de stare: starea din browser, prin cookie-uri și filtre persistente, și starea aplicației, prin clase care separă accesul la bază, rolurile, drepturile și utilizatorul.")

    requirement(doc, "7.1 Carduri Bootstrap animate", "Cardurile produselor trebuie să apară succesiv la momentele t, 2t, 3t și așa mai departe, folosind JavaScript și componenta Bootstrap card.", "Produsele reale generate din PostgreSQL primesc clasele card. animeazaCarduriBootstrap() parcurge NodeList-ul și programează adăugarea clasei vizibile cu setTimeout((index+1)*t).", "setTimeout nu oprește pagina; el programează o funcție pentru mai târziu. Fiecare index produce o întârziere diferită. CSS definește starea inițială și finală, iar JavaScript decide momentul schimbării.", "EJS produce toate cardurile, Bootstrap le dă structura, CSS definește tranziția, iar JavaScript adaugă clasa vizibilă succesiv.", "views/pagini/produse.ejs, resurse/js/produse.js și resurse/sass/etapa7.scss")

    requirement(doc, "7.2 Bannerul animat și acceptul cookie", "Bannerul fix trebuie să intre prin animație, să ceară acceptul și să nu reapară timp de o săptămână după apăsarea Ok.", "banner-cookies.ejs păstrează structura cerută. CSS rulează animația de cinci secunde. cookies.js citește cookie-ul, afișează bannerul numai dacă lipsește și setează acceptul cu expirare de șapte zile.", "Cookie-ul este un șir nume=valoare cu atribute precum expires, path și SameSite. Browserul îl trimite la cererile corespunzătoare domeniului. CSS nu poate ști singur dacă utilizatorul a acceptat; JavaScript ia această decizie înainte de afișare.", "Animația este exclusiv CSS, iar persistența deciziei este JavaScript plus cookie. La refresh, existența cookie-ului împiedică reapariția bannerului.", "views/fragmente/banner-cookies.ejs, resurse/js/cookies.js și resurse/sass/etapa7.scss")

    requirement(doc, "7.3 Funcțiile cookie și cookie-urile suplimentare", "Trebuie funcții separate de citire, setare și ștergere și încă un cookie relevant site-ului.", "cookies.js definește citesteCookie, seteazaCookie, deleteCookie și deleteAllCookies. În plus, sunt memorate ultima pagină și ultimul produs vizitat, fără parole sau informații sensibile.", "O funcție separată evită repetarea sintaxei document.cookie. path=/ face cookie-ul disponibil pe întregul site. SameSite=Lax reduce trimiterea cookie-ului în contexte externe, iar expirarea stabilește când este eliminat.", "Am centralizat operațiile cookie și am salvat numai context de navigare, nu credențiale.", "resurse/js/cookies.js")

    requirement(doc, "7.4 Clasa AccesBD și Singleton", "Accesul la baza de date trebuie centralizat într-o singură instanță, cu metode CRUD callback și async.", "module/acces-bd.js păstrează o instanță statică și un singur Pool PostgreSQL. Constructorul împiedică o a doua instanțiere. Metodele select, insert, update și delete validează identificatorii, parametrizează valorile și pot apela un callback.", "Singleton nu înseamnă o singură conexiune fizică, ci un singur obiect responsabil de Pool și de construirea query-urilor. Pool-ul administrează conexiuni reutilizabile. Callbackul primește eroarea și rezultatul; varianta async returnează un Promise și poate fi apelată cu await.", "Am un singur punct controlat de acces la baza de date. Clasa nu concatenează valorile utilizatorului în SQL, ci folosește parametri separați.", "module/acces-bd.js")

    requirement(doc, "7.5 Drepturi, roluri și Factory", "Drepturile trebuie reprezentate prin Symbol, iar RolFactory trebuie să creeze subclasa potrivită după cod.", "drepturi.js exportă drepturile unice. roluri.js definește Rol, RolComun, RolClient, RolModerator, RolManagerProduse și RolAdmin. creeazaRol(cod) întoarce obiectul potrivit, iar areDreptul verifică Set-ul de drepturi.", "Symbol are identitate unică: două simboluri cu aceeași descriere nu sunt egale. Set evită duplicatele și verifică rapid apartenența. Factory ascunde alegerea constructorului; restul aplicației cere un rol prin cod și nu trebuie să cunoască toate clasele.", "Am separat numele rolului de drepturile efective. Factory transformă codul din bază în obiectul potrivit, iar areDreptul lucrează cu simboluri unice.", "module/drepturi.js și module/roluri.js")

    requirement(doc, "7.6 Clasa Utilizator", "Utilizatorul trebuie modelat printr-o clasă cu validări, operații în bază, căutări sync/async, verificarea drepturilor și trimiterea de e-mail.", "module/utilizator.js mapează câmpurile tabelului, aplică valori implicite, validează nume, username și e-mail, delegă operațiile CRUD către AccesBD, reconstruiește rolul prin RolFactory și delegă mesajele către modulul de e-mail.", "Clasa reprezintă un utilizator ca obiect, nu ca un set de variabile fără legătură. Constructorul primește un obiect, ceea ce face ordinea argumentelor irelevantă. Metodele de instanță lucrează cu utilizatorul curent; metodele statice caută utilizatori fără să existe deja o instanță.", "Clasa Utilizator reunește regulile proprii entității, dar nu deschide conexiuni și nu implementează SMTP; deleagă aceste responsabilități modulelor specializate.", "module/utilizator.js, module/acces-bd.js și module/email.js")

    requirement(doc, "7.7 Documentarea JSDoc", "Clasele și funcțiile proprii trebuie documentate cu scop, parametri și rezultat.", "Modulele și funcțiile principale au blocuri /** ... */ cu @param, @returns și explicații. Comentariile de etapă indică și cerința asociată.", "JSDoc nu schimbă execuția programului. Este o convenție structurată pe care editorul și generatoarele de documentație o pot interpreta. Un comentariu bun explică contractul funcției, nu repetă fiecare linie.", "Pentru funcțiile publice explic ce primesc, ce întorc și ce erori pot produce. Comentariile cu etapa ajută la identificarea cerinței la prezentare.", "index.js și toate fișierele din module/")

    bonus(doc, "1", "Operator OR în query builder", "0,3 p", "Condițiile CRUD trebuie să poată combina grupuri AND prin OR.", "AccesBD acceptă condiții grupate și generează paranteze cu operatori controlați, păstrând valorile parametrizate.", "Vectorul exterior reprezintă alternative OR, iar fiecare vector interior condiții simultane AND. Parantezele păstrează prioritatea logică.", "Am extins query builderul fără să accept SQL arbitrar de la utilizator; structura condițiilor este controlată și valorile rămân parametri.", "module/acces-bd.js", "implementat")
    bonus(doc, "2", "ORM Sequelize", "0,4 p", "Un ORM trebuie folosit, cu Singleton implementat în altă zonă.", "module/acces-orm.js definește modelul ProdusORM și folosește findAll pentru selecția produselor noi.", "ORM-ul mapează o tabelă la un model JavaScript și transformă metode precum findAll în SQL. În proiect este demonstrată integrarea fără a elimina AccesBD cerut obligatoriu.", "Pot arăta atât query builderul Singleton cerut la bază, cât și o interogare echivalentă exprimată prin modelul Sequelize.", "module/acces-orm.js și package.json", "implementat ca integrare punctuală; punctajul complet depinde dacă profesoara cere înlocuirea tuturor query-urilor")
    bonus(doc, "3", "Filtre persistente", "0,4 p", "Ultima filtrare trebuie salvată și restaurată dacă utilizatorul bifează opțiunea.", "produse.js serializează valorile celor opt filtre în localStorage. La încărcare, reface inputurile și reaplică filtrarea. Resetarea șterge cheia și debifează opțiunea.", "JSON.stringify transformă obiectul de stare în text, singurul format acceptat de localStorage; JSON.parse îl reconstruiește.", "Salvez starea formularului, nu rezultatul HTML. La revenire refac inputurile și las aceeași funcție de filtrare să regenereze rezultatul.", "resurse/js/produse.js și views/pagini/produse.ejs", "implementat")


def add_stage8(doc):
    doc.add_page_break()
    base.add_heading(doc, "Etapa 8 - sistemul complet de utilizatori", 1)
    base.add_para(doc, "Etapa 8 transformă clasele pregătite anterior într-un sistem real de conturi. Fluxul complet este: formular în browser, validare client, validare server, salvare securizată, confirmare e-mail, login, sesiune, profil și autorizare.")

    mandatory = [
        ("8.1 Structura tabelei utilizatori", "Tabela trebuie să conțină identitate, username, e-mail, parolă, date, rol, blocare, imagine și preferințe.", "Migrarea extinde tabela în mod idempotent, cu coloane și valori DEFAULT. Imaginea este salvată ca drum, nu ca binar.", "Schema bazei este contractul datelor. DEFAULT oferă o stare validă chiar dacă formularul nu trimite un câmp opțional. ALTER ... IF NOT EXISTS permite rerularea migrației.", "Am extins baza fără să pierd datele existente și am ales tipuri potrivite fiecărei proprietăți.", "database/05-etapa8-utilizatori.sh și database/06-bonusuri-etapele6-8.sql"),
        ("8.2 Formularul de înregistrare", "Formularul trebuie să includă câmpurile obligatorii, repetarea parolei, data nașterii, culoarea și imaginea opțională.", "inregistrare.ejs folosește enctype multipart/form-data. Multer primește fișierul, Sharp validează și redimensionează imaginea, iar valorile text ajung în req.body.", "Formularele normale trimit text. multipart este necesar când există fișier. Multer separă câmpurile și fișierul; Sharp verifică dacă uploadul chiar este imagine și produce o dimensiune controlată.", "Am tratat uploadul separat de datele text și salvez în bază doar calea imaginii procesate.", "views/pagini/inregistrare.ejs, module/rute-utilizatori.js și resurse/js/utilizatori.js"),
        ("8.3 Validarea client și server", "Câmpurile obligatorii, parolele, e-mailul, username-ul și vârsta trebuie verificate înainte de salvare.", "Browserul oferă feedback imediat, iar serverul repetă aceleași reguli în valideazaInregistrare(). Serverul verifică suplimentar unicitatea în PostgreSQL.", "JavaScript din browser poate fi dezactivat sau modificat, deci nu este o barieră de securitate. Serverul este autoritatea finală. Validarea dublă nu este duplicare inutilă: clientul optimizează experiența, serverul protejează datele.", "Validez de două ori din motive diferite: rapiditate pentru utilizator și siguranță pentru aplicație.", "resurse/js/utilizatori.js, module/rute-utilizatori.js și module/utilizator.js"),
        ("8.4 Parola, saltul și scrypt", "Parola nu trebuie salvată în clar, iar utilizatorul primește confirmare numai dacă toate datele sunt valide.", "securitate.js generează salt aleator și derivă parola cu crypto.scryptSync. În tabel sunt salvate saltul și rezultatul derivării. La login se repetă derivarea și se compară cu timingSafeEqual.", "Hashul parolei este un proces unidirecțional: aplicația nu poate recupera parola originală. Saltul face ca două parole identice să producă rezultate diferite. timingSafeEqual reduce diferențele de timp care ar putea divulga informații.", "Parola nu este criptată pentru a fi decriptată; este derivată unidirecțional cu scrypt și salt unic.", "module/securitate.js și module/rute-utilizatori.js"),
        ("8.5 Confirmarea adresei de e-mail", "După înregistrare trebuie trimis un link cu două tokenuri, iar contul nu poate face login înainte de confirmare.", "Sunt generate două tokenuri aleatoare și salvate. Linkul /confirmare/:username/:token1/:token2 activează contul numai dacă toate valorile coincid. În mediul local, mesajul este salvat în log pentru demonstrație.", "Tokenul este o dovadă greu de ghicit. Două tokenuri reduc și mai mult posibilitatea unei confirmări accidentale. Nodemailer este configurabil: SMTP real când există credențiale, transport JSON local la dezvoltare.", "Contul există, dar rămâne neconfirmat până când utilizatorul dovedește accesul la adresa de e-mail prin linkul unic.", "module/email.js și module/rute-utilizatori.js"),
        ("8.6 Loginul", "Autentificarea trebuie să verifice existența, confirmarea, blocarea și parola.", "Ruta /login caută utilizatorul, respinge conturile neconfirmate sau blocate, recalculează parola cu saltul din bază și creează sesiunea la succes.", "Loginul este o comparație între dovada introdusă și rezultatul păstrat. Mesajele sunt controlate pentru a nu divulga inutil dacă un username există. La succes se actualizează ultima logare și activitatea.", "Nu compar parole în clar. Recalculez derivarea cu saltul utilizatorului și creez sesiunea numai după toate verificările.", "module/rute-utilizatori.js, module/securitate.js și views/fragmente/header.ejs"),
        ("8.7 Sesiunea și logoutul", "Utilizatorul trebuie păstrat autentificat între cereri și delogat explicit.", "express-session păstrează pe server datele minime ale utilizatorului. Browserul primește doar identificatorul sesiunii. Logoutul distruge sesiunea și redirecționează.", "Sesiunea rezolvă faptul că HTTP nu ține minte automat cererea anterioară. Cookie-ul de sesiune nu conține parola sau toate datele; el indică o înregistrare de pe server.", "În sesiune păstrez numai datele necesare afișării și autorizării. Logoutul distruge acea stare pe server.", "index.js și module/rute-utilizatori.js"),
        ("8.8 Headerul utilizatorului autentificat", "În locul formularului de login trebuie afișate username-ul, numele complet la hover, rolul, avatarul și logoutul.", "header.ejs verifică utilizatorCurent. Dacă există, afișează imaginea, username-ul cu title, badge de rol și linkul Logout; altfel păstrează formularul.", "EJS folosește aceeași sursă de sesiune pentru a genera două ramuri HTML. Asta este personalizare pe server, nu ascundere ulterioară cu CSS.", "Serverul decide ce versiune a headerului trimite. Totuși, ascunderea linkurilor admin nu înlocuiește autorizarea rutelor.", "views/fragmente/header.ejs"),
        ("8.9 Profilul", "Pagina de profil trebuie precompletată, username-ul readonly și orice modificare verificată prin parola curentă.", "Ruta protejată citește datele din PostgreSQL. La POST verifică parola, procesează eventual noul avatar, generează un salt nou dacă parola se schimbă și sincronizează sesiunea.", "readonly împiedică editarea normală în interfață, dar serverul tot nu acceptă schimbarea username-ului. Verificarea parolei demonstrează că persoana care are sesiunea cunoaște și secretul contului.", "Profilul nu are încredere doar în sesiunea deschisă: pentru modificări sensibile cer din nou parola curentă.", "views/pagini/profil.ejs și module/rute-utilizatori.js"),
        ("8.10 Administrarea utilizatorilor", "Minimum doi administratori trebuie să poată vedea utilizatorii, bloca/debloca și avea pagini speciale.", "middleware-ul necesitaAdmin verifică rolul înainte de rute. Tabelul Bootstrap exclude administratorul curent. Butonul de blocare trimite fetch, serverul actualizează baza și răspunde JSON.", "Autorizarea reală este pe server. Un utilizator poate scrie manual URL-ul chiar dacă linkul nu se vede, dar middleware-ul oprește cererea cu 403. Fetch permite actualizarea rândului fără refresh.", "Ascund meniul pentru claritate, dar protecția adevărată este necesitaAdmin executat înaintea handlerului.", "module/rute-utilizatori.js, views/pagini/administrare-utilizatori.ejs și resurse/js/admin-utilizatori.js"),
        ("8.11 Administrarea produselor", "Adminul trebuie să poată adăuga, modifica și șterge produse.", "Pagina administrare-produse folosește formulare server-side, query-uri parametrizate și valorile ENUM existente. Stocul este numeric și actualizarea poate declanșa notificările favorite.", "CRUD înseamnă Create, Read, Update, Delete. Valorile sunt trimise separat de SQL, iar categoria este verificată față de tipurile cunoscute.", "Am reutilizat aceeași bază și reguli de validare; adminul nu modifică direct fișierul SQL sau HTML-ul.", "index.js și views/pagini/administrare-produse.ejs"),
        ("8.12 Utilizatorii online", "Trebuie afișați administratorii activi în ultimele zece minute și actualizați periodic.", "Middleware-ul actualizează ultima_activitate cel mult o dată pe minut. /api/admini-online returnează JSON, iar utilizatori-online.js reia fetchul la interval și actualizează lista.", "Activitatea online este o aproximare bazată pe ultima cerere. Limitarea actualizării la un minut evită câte un UPDATE la fiecare imagine sau pagină.", "Consider online un administrator cu activitate recentă și actualizez lista fără reîncărcare.", "index.js și resurse/js/utilizatori-online.js"),
        ("8.13 Ștergerea contului și politica", "Utilizatorul trebuie să poată cere ștergerea cu parola, să primească e-mail și să poată consulta politica de confidențialitate.", "Ruta de ștergere verifică parola, trimite mesajul, elimină utilizatorul și distruge sesiunea. Pagina de politică explică datele, cookie-urile și drepturile, iar linkul apare în formular și footer.", "Ștergerea cere reautentificare deoarece este ireversibilă. Distrugerea sesiunii este necesară fiindcă utilizatorul nu mai există după operație.", "Nu permit ștergerea doar printr-un click într-o sesiune deschisă; cer parola și închei sesiunea după eliminarea contului.", "module/rute-utilizatori.js și views/pagini/politica-confidentialitate.ejs"),
    ]
    for args in mandatory:
        requirement(doc, *args)

    bonuses = [
        ("1", "Salt unic", "0,15 p", "Fiecare utilizator trebuie să aibă alt salt.", "randomBytes generează saltul și acesta este stocat pe utilizator.", "Saltul împiedică identificarea parolelor egale prin hashuri egale.", "Fiecare rând are propriul salt; nu există un secret global reutilizat.", "module/securitate.js", "implementat"),
        ("2", "Tema salvată pe server", "0,2 p", "Tema utilizatorului logat trebuie restaurată la login.", "POST /api/tema actualizează coloana tema, iar sesiunea și tema.js îi acordă prioritate față de localStorage.", "Preferința din cont se poate muta între browsere după autentificare; localStorage rămâne fallback pentru vizitatori.", "Pentru un cont logat, baza este sursa preferinței; pentru vizitator folosesc memoria locală.", "resurse/js/tema.js și module/rute-utilizatori.js", "implementat"),
        ("3", "Conturi neconfirmate", "0,15 p", "După t1 trebuie notificare, iar după t1+t2 contul trebuie șters automat.", "Un interval caută conturile și trimite notificarea o singură dată. Codul de ștergere este controlat prin activeazaStergereConturiNeconfirmate din JSON și este implicit oprit.", "Procesul periodic rulează independent de cererea utilizatorului. Separarea notificării de ștergere permite demonstrarea sigură fără pierdere accidentală.", "Notificarea este activă. Ștergerea este pregătită, dar nu o prezint ca activă până nu setez explicit opțiunea pentru un test controlat.", "index.js și resurse/json/optiuni-server.json", "parțial activ: notificare da, ștergere implicit nu"),
        ("4", "Recuperarea parolei", "0,2 p", "Utilizatorul care a uitat parola trebuie să primească un link temporar.", "Serverul generează token aleator cu expirare de 30 de minute. Pagina de resetare validează tokenul, salvează parola cu salt nou și invalidează tokenul.", "Tokenul înlocuiește temporar dovada parolei vechi, dar este valabil o singură dată și într-un interval scurt.", "Nu trimit parola prin e-mail. Trimit un link temporar care permite setarea unei parole noi.", "views/pagini/recuperare-parola.ejs, views/pagini/resetare-parola.ejs și module/rute-utilizatori.js", "implementat"),
        ("5", "Sugestii de username", "0,3 p", "Dacă username-ul există, trebuie propuse variante libere.", "sugereazaUsername() generează candidați și verifică în PostgreSQL până găsește trei liberi.", "O sugestie este utilă numai dacă este verificată față de baza actuală; adăugarea aleatoare a unui număr nu garantează unicitatea.", "Generez variante, dar le afișez numai după ce confirm că nu există în tabel.", "module/rute-utilizatori.js", "implementat"),
        ("6", "Blocarea loginului", "0,2 p", "Cinci parole greșite în zece minute trebuie să blocheze loginul o oră și să trimită avertizare.", "Tabela păstrează numărul, începutul ferestrei și blocarea până la. Loginul actualizează atomar starea și trimite e-mail la atingerea pragului.", "Fereastra de timp evită blocarea permanentă pentru încercări rare. Data blocării permite serverului să decidă automat când expiră.", "Contorizez încercările într-o fereastră și blochez temporar, nu definitiv; proprietarul primește avertizare.", "database/06-bonusuri-etapele6-8.sql și module/rute-utilizatori.js", "implementat"),
        ("7", "Mod mentenanță", "0,2 p", "Un flag JSON trebuie să transforme toate cererile într-o pagină 503.", "Middleware-ul citește opțiunea și răspunde cu mentenanta.ejs înaintea rutelor normale, exceptând resursele necesare și administrarea controlată.", "Middleware-ul app.use se execută în ordinea înregistrării. HTTP 503 spune corect că serviciul este temporar indisponibil.", "Schimb un flag, nu rescriu rutele. Middleware-ul interceptează central cererile și folosește statusul semantic 503.", "index.js, resurse/json/optiuni-server.json și views/pagini/mentenanta.ejs", "implementat"),
        ("8", "Timp de la ultima logare", "0,1 p", "Prima pagină trebuie să exprime diferența în zile, ore și minute.", "formateazaTimpTrecut() descompune diferența dintre Date.now() și ultima_logare și produce textul.", "Milisecundele sunt transformate progresiv în minute, ore și zile folosind împărțire și rest.", "Transform o dată tehnică într-un mesaj ușor de înțeles pentru utilizator.", "module/rute-utilizatori.js și views/pagini/index.ejs", "implementat"),
        ("9", "Sesiune configurabilă și «Reține»", "0,2 p", "Sesiunea trebuie să expire după M minute, cu opțiune extinsă.", "Durata normală vine din optiuni-server.json, iar checkboxul ramai_conectat setează o perioadă mai lungă pentru cookie.", "maxAge controlează viața cookie-ului de sesiune; nu stocăm parola pentru a reface loginul.", "Opțiunea extinde durata sesiunii, nu salvează credențialele în browser.", "index.js, views/fragmente/header.ejs și module/rute-utilizatori.js", "implementat"),
        ("10", "E-mail promoțional", "0,15 p", "Conturile inactive trebuie contactate cel mult o dată pe lună și mesajul să aibă imagine.", "Procesul periodic selectează conturile eligibile, verifică ultima_promotie și trimite HTML cu imagine atașată.", "Coloana ultima_promotie previne spamul la fiecare verificare a intervalului.", "Separ criteriul de inactivitate de frecvența mesajului și înregistrez momentul ultimei promoții.", "index.js, module/email.js și database/06-bonusuri-etapele6-8.sql", "implementat"),
        ("11", "Roluri și drepturi în baze de date", "0,55 p", "Rolurile, drepturile și asocierile trebuie modelate în tabele, cu perioade de valabilitate și pagină admin.", "Migrarea creează roluri, drepturi, roluri_drepturi și utilizatori_roluri. Pagina administrare-roluri permite atribuirea și intervalele, iar clasele includ manager_produse.", "Relația separată permite unui utilizator mai multe roluri și fiecărui rol mai multe drepturi. NULL în date înseamnă perioadă nedeterminată.", "Am trecut de la un singur text rol la o structură many-to-many, pregătită pentru perioade și drepturi granulare.", "database/06-bonusuri-etapele6-8.sql, module/roluri.js și views/pagini/administrare-roluri.ejs", "implementat; unele middleware-uri vechi păstrează și verificarea rolului principal pentru compatibilitate"),
        ("12", "Site actualizat", "0,35 p", "Data footerului trebuie calculată din cel mai nou produs și cea mai nouă modificare EJS, apoi comparată cu ultima vizită.", "Serverul parcurge template-urile, citește data maximă din bază și expune valoarea. site-actualizat.js afișează mesajul trei secunde când vizita este mai veche.", "Maximul dintre cele două date descrie ultima schimbare relevantă de conținut sau prezentare. Starea vizitei este memorată separat.", "Data nu este scrisă manual în footer; este calculată din fișiere și produse.", "index.js și resurse/js/site-actualizat.js", "implementat"),
        ("13", "Produse favorite", "0,7 p", "Utilizatorii logați trebuie să salveze favorite, să vadă marcaje și contoare, iar adminul să aibă top și reumplere stoc.", "Tabela favorite păstrează perechea utilizator-produs. Butoanele folosesc fetch, contoarele se actualizează la cinci secunde, /favorite listează selecția, iar /top-favorite permite reumplerea și declanșează avertizarea de stoc redus.", "Cheia unică împiedică duplicarea aceleiași favorite. COUNT grupează preferințele. Notificarea este legată de schimbarea stocului și include informațiile produsului.", "Favoritele sunt date persistente, nu iconuri locale. Numărul este agregat din tabel și se actualizează fără refresh.", "database/06-bonusuri-etapele6-8.sql, resurse/js/favorite.js, views/pagini/favorite.ejs și views/pagini/top-favorite.ejs", "implementat în mare parte; e-mailul duce la pagina produsului, nu la un coș virtual care nu a fost încă implementat"),
    ]
    for item in bonuses:
        if item[0] == "2":
            # ETAPA 8, BONUS 2: pagina nouă păstrează eticheta „Ce am făcut” lângă explicația ei în PDF.
            doc.add_page_break()
        bonus(doc, *item)


def add_stage10(doc):
    doc.add_page_break()
    base.add_heading(doc, "Etapa 10 - aspect și finisare vizuală", 1)
    base.add_para(doc, "Scopul nu a fost o redesenare spectaculoasă care să ascundă etapele anterioare. Am păstrat identitatea roșu-gri-alb și am unificat detaliile care fac diferența între o pagină funcțională și una îngrijită.")
    requirement(doc, "10.1 Variabile vizuale comune", "Aspectul trebuie îmbunătățit coerent, fără reguli contradictorii între pagini.", "etapa10.scss definește variabile pentru roșu, vișiniu, suprafață, rază și umbră. Cardurile, panourile și secțiunile importante refolosesc aceste valori.", "O variabilă CSS este o valoare cu nume. Dacă schimb raza într-un singur loc, toate componentele care folosesc var(--forge-raza) se actualizează. Acest lucru previne diferențe accidentale între carduri.", "Am centralizat finisajele în variabile și într-un fișier încărcat ultimul, astfel încât Etapa 10 îmbunătățește fără să rescrie logica.", "resurse/sass/etapa10.scss și views/fragmente/head.ejs")
    requirement(doc, "10.2 Interacțiuni și focus", "Butoanele și cardurile trebuie să răspundă plăcut la interacțiune și să rămână accesibile cu tastatura.", "Hoverul ridică discret elementele, focus-visible adaugă contur clar, iar tranzițiile sunt scurte. prefers-reduced-motion elimină mișcarea pentru utilizatorii care au această preferință.", "Hover este feedback pentru mouse, iar focus-visible este feedback pentru tastatură. Transform schimbă prezentarea fără să mute celelalte elemente din layout. Media query-ul de accesibilitate respectă setarea sistemului de operare.", "Nu am folosit animații mari. Am adăugat feedback discret și focus vizibil, dar dezactivez mișcarea când utilizatorul cere reduced motion.", "resurse/sass/etapa10.scss")
    doc.add_page_break()
    requirement(doc, "10.3 Responsive și eliminarea scrollului orizontal", "Pagina trebuie să rămână utilizabilă pe desktop, ecran mediu și mobil.", "Tabelele din carduri suprascriu min-width-ul global, meniul poate trece pe două rânduri între 1101 și 1450 px, iar pe 390 px este folosit hamburgerul. Grilele ajung la o singură coloană.", "Scrollul orizontal apare când un copil are lățime minimă mai mare decât părintele. Soluția corectă este locală: eliminăm min-width doar pentru tabelul cardului, nu ascundem overflowul întregii pagini și nu mascăm problema.", "Am identificat elementul care depășea viewportul și am corectat regula la sursă. Am verificat programatic că scrollWidth este egal cu clientWidth pe desktop și mobil.", "resurse/sass/produse.scss și resurse/sass/etapa10.scss")
    requirement(doc, "10.4 De ce aspectul a rămas apropiat", "Finisarea trebuie să îmbunătățească proiectul fără să piardă tema sau să transforme secțiunile în demonstrații fără legătură.", "Am păstrat paleta și structura, am folosit conținut PC Forge real, umbre mai discrete, spațiere consecventă și raze comune. Secțiunea Bootstrap explică tema, gridul și compilarea SCSS.", "Un design coerent nu înseamnă că toate elementele sunt identice. Înseamnă că folosesc aceeași familie de culori, aceeași scară de spațiere și aceleași convenții de interacțiune. Conținutul trebuie să susțină tema site-ului.", "Am făcut modificări mici și sistematice. Rezultatul arată mai îngrijit, dar profesoara poate recunoaște în continuare toate etapele și cerințele.", "resurse/sass/etapa10.scss și views/pagini/index.ejs")


def add_presentation_walkthrough(doc):
    doc.add_page_break()
    base.add_heading(doc, "Cum să decurgă prezentarea", 1)
    base.add_para(doc, "Începe cu rezultatul din browser și deschide codul numai după ce ai explicat ce vede utilizatorul. Pentru fiecare funcționalitate urmează aceeași ordine: demonstrație, traseul datelor, fișierul principal și motivul soluției.")
    for number, text in enumerate([
        "Arată prima pagină, secțiunea Bootstrap și efectele CSS. Explică diferența dintre componentă Bootstrap, regulă CSS proprie și SCSS compilat.",
        "Arată galeriile, apoi galerie.json. Explică de ce imaginile sunt date și de ce EJS generează HTML-ul.",
        "Modifică o valoare SCSS și arată recompilarea și backupul cu timestamp.",
        "Deschide /produse. Demonstrează toate filtrele, validarea, două chei de sortare, calculul și resetarea.",
        "Arată paginarea, fixarea, ascunderile, modalul, filtrarea server și comparația.",
        "Deschide un produs, caruselul, produsele similare și seturile; apoi arată produsele noi și oferta.",
        "Demonstrează cookie bannerul și explică diferența dintre cookie, localStorage, sessionStorage și sesiunea Express.",
        "În cod, urmărește AccesBD -> Utilizator -> RolFactory -> Drepturi. Nu încerca să explici toate metodele simultan; alege câte un exemplu.",
        "Creează sau folosește un cont demonstrativ: confirmare, login, temă, profil, recuperare parolă și logout.",
        "Cu un admin, arată blocarea, produsele, rolurile, topul favoritelor și utilizatorii online.",
        "Încheie cu Etapa 10: redimensionează fereastra, arată lipsa scrollului orizontal și explică de ce stilurile sunt într-un fișier separat.",
    ], 1):
        base.add_heading(doc, f"Pasul {number}", 2)
        base.add_para(doc, text)


def add_glossary_prose(doc):
    doc.add_page_break()
    base.add_heading(doc, "Termeni tehnici explicați pe scurt", 1)
    definitions = [
        ("EJS", "un template HTML executat pe server. Primește obiecte JavaScript și produce HTML final înainte ca răspunsul să ajungă în browser."),
        ("SCSS", "o sintaxă Sass cu variabile, bucle și organizare mai bună. Browserul nu o citește direct; proiectul o compilează în CSS."),
        ("DOM", "reprezentarea paginii ca obiecte JavaScript. Când ascunzi un card sau creezi un mesaj, modifici DOM-ul."),
        ("Middleware", "o funcție Express executată între primirea cererii și răspuns. Poate adăuga date, autoriza, bloca sau transmite mai departe prin next()."),
        ("Promise și async/await", "un Promise reprezintă un rezultat viitor. await așteaptă acel rezultat în interiorul unei funcții async, fără să blocheze întregul server."),
        ("Query parametrizat", "textul SQL conține $1, $2, iar valorile sunt trimise separat. Astfel datele utilizatorului nu sunt interpretate drept comenzi SQL."),
        ("Singleton", "un pattern care garantează că aplicația folosește un singur obiect principal pentru o responsabilitate, aici accesul la Pool-ul bazei."),
        ("Factory", "un obiect sau o clasă care alege ce instanță să creeze. Apelantul oferă codul rolului, iar RolFactory alege constructorul."),
        ("Cookie", "o valoare mică asociată domeniului, cu expirare și reguli de trimitere. În proiect reține acceptul și identificatorul sesiunii."),
        ("localStorage", "memorie persistentă numai în browser. Este folosită pentru tema vizitatorului, filtre și comparare."),
        ("sessionStorage", "memorie a unui singur tab. Dispare la închiderea tabului și este potrivită pentru ascunderea produselor doar în sesiunea vizuală curentă."),
        ("Sesiune Express", "stare păstrată pe server pentru utilizatorul autentificat. Browserul are doar cookie-ul care identifică sesiunea."),
        ("Salt", "șir aleator diferit pentru fiecare parolă, folosit înaintea derivării pentru ca parolele identice să nu aibă rezultate identice."),
        ("Token", "șir aleator greu de ghicit, folosit ca dovadă temporară la confirmarea e-mailului sau resetarea parolei."),
        ("ORM", "un strat care reprezintă tabelele ca modele și interogările ca metode JavaScript, de exemplu ProdusORM.findAll()."),
    ]
    for term, explanation in definitions:
        p(doc, f"{term}:", explanation)


def build():
    OUT.parent.mkdir(parents=True, exist_ok=True)
    doc = base.setup_document()
    configure_narrative_style(doc)
    add_cover(doc)
    add_intro(doc)
    add_stage5(doc)
    add_stage6(doc)
    add_stage7(doc)
    add_stage8(doc)
    add_stage10(doc)
    add_presentation_walkthrough(doc)
    add_glossary_prose(doc)
    base.apply_romanian_diacritics(doc)
    doc.save(OUT)
    print(OUT)


if __name__ == "__main__":
    build()
